### PR TITLE
Rewrite computed properties with new syntax to suppress deprecation warnings

### PR DESCRIPTION
**Pull request by crudo1f**
Ember.js 1.12 introduced an improved syntax[1] for computed properties with
a setter:

```
DEPRECATION: Using the same function as getter and setter is deprecated. See http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter for more details.
        at ComputedProperty (http://localhost:7357/static-assets/vendor.js:20233)
        at computed (http://localhost:7357/static-assets/vendor.js:20694)
        at http://localhost:7357/static-assets/vendor.js:79924
        at http://localhost:7357/static-assets/vendor.js:80572
```

Use new getter and setter syntax instead of checking arguments.length and add Ember version 1.13.2.

**Caveat**: this change is not compatible with Ember version below 1.12.0. In Ember 1.11.x the
        "new-computed-syntax" feature has to be explicitly enabled to make this work,
        see https://github.com/rwjblue/ember.js/commit/9ee6d7c5db965ab0408fa77dc6e624d7ad322431.

### CODE REVIEW

**Comment by avdv** [comment]
Hi.

Fixing all the deprecations is vital for Ember 2.0 support since all the deprecated things will be removed in the final release.

Since Ember 2.0 is now due in a few days, I wanted to ask what's the plan for ember-resource in supporting it?

Do you intend to create a `2.x` branch or just remove the old cruft (support for Ember < 1.12) and be done with it?

Thanks!

**Comment by shajith** [comment]
@avdv: Sorry about the lag here! We've been busy with our own migration..

We need to maintain support for < 1.12 for our internal use case, while we upgrade, so we intend to  create a 2.x branch to continue development.

**Comment by ducarroz** [comment]
on way to keep the code backward compatible with < 1.12 is to dynamically define the properties `propertyFunction ` and `content` in the init method with a switch for ember pre-1.12...

**Comment by crudo1f** [comment]
I think a 2.x branch should be easier to maintain and I can't imagine a real usecase where it is helpful to have backward compatible code.

**Comment by avdv** [comment]
> @avdv: Sorry about the lag here! We've been busy with our own migration..

No problem. I justed wanted to give a quick heads-up. Countdown is running... ;-)

> We need to maintain support for < 1.12 for our internal use case, while we upgrade, so we intend to create a 2.x branch to continue development.

Thanks for your info!

**Comment by avdv** [comment]
Hi.

We now have completely eliminated all deprecation warnings which were blocking adaptation of Ember.js 2 and successfully upgraded to Ember.js 1.13.10 for the "current" and Ember.js 2.0.2 in the "next" version.

The ember-resource version was bumped to `2.2.0`, in lieu of a better idea.

See the "ember-2.0" branch in the [eXa-online/ember-resource](https://github.com/eXa-online/ember-resource) repository.

We would like to integrate this branch back into zendesk's repository. If you create a new branch we could create a pull request. What do you think?

**Comment by crudo1f** [comment]
Close this request because [#117](https://github.com/zendesk/ember-resource/issues/117) was merged.
Thanks for that.

**Pull request closed without merging**
